### ISSUE TITLE
webpack@2 support

### ISSUE THREAD

**Issue by JSteunou** [mistadikay/strict-loader#7]
even if if still in beta, would be nice to be able to support it.

**Comment by mistadikay** [comment]
@JSteunou yep, I will probably do it this weekend, but if you'll submit PR — it might speed things up. Thanks

**Comment by JSteunou** [comment]
nothing fancy, already working, it's just npm yelling at install because of `peerDependencies`. Better to remove it also npmv3 change its behavior.

**Comment by mistadikay** [comment]
fixed in [v1.1.0](https://github.com/mistadikay/strict-loader/releases/tag/v1.1.0)

**Comment by JSteunou** [comment]
Nice, thank you!
